delimiter //
CREATE DEFINER=`root`@`localhost` FUNCTION `MOYANNUELLE`(`V1` DECIMAL(9,6), `V2` DECIMAL(9,6), `V3` DECIMAL(9,6), `V4` DECIMAL(9,6), `V5` DECIMAL(9,6), `V6` DECIMAL(9,6)) RETURNS decimal(9,6)
BEGIN 
	DECLARE NBCOUNT  NUMERIC;
	DECLARE TOTAL  NUMERIC;
	DECLARE DIVISION_BY_ZERO CONDITION FOR SQLSTATE '22012';
	DECLARE EXIT HANDLER FOR DIVISION_BY_ZERO RETURN NULL;
    SET NBCOUNT = 0;
    SET TOTAL = 0;
    IF V1 IS NOT NULL THEN SET NBCOUNT = NBCOUNT+1; SET TOTAL = TOTAL+V1; END IF;
    IF V2 IS NOT NULL THEN SET NBCOUNT = NBCOUNT+1; SET TOTAL=TOTAL+V2; END IF;
    IF V3 IS NOT NULL THEN SET NBCOUNT=NBCOUNT+1; SET TOTAL=TOTAL+V3; END IF;
    IF V4 IS NOT NULL THEN SET NBCOUNT=NBCOUNT+1; SET TOTAL=TOTAL+V4; END IF;
    IF V5 IS NOT NULL THEN SET NBCOUNT=NBCOUNT+1; SET TOTAL=TOTAL+V5; END IF;
    IF V6 IS NOT NULL THEN SET NBCOUNT=NBCOUNT+1; SET TOTAL=TOTAL+V6; END IF;
    RETURN TOTAL/NBCOUNT;
END//
